#!/usr/bin/python

import argparse
import jinja2
import tempfile
import subprocess

role_playbook = '''---
- hosts: {{hosts}}
  gather_facts: {{gather}}
  roles:
    - role: {{role}}

'''


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--verbose', '-v',
                   action='count',
                   default=0)

    p.add_argument('--gather', '-g',
                   action='store_true')
    p.add_argument('--no-gather', '-G',
                   action='store_false',
                   dest='gather')
    p.add_argument('--extra-vars', '-e',
                   action='append',
                   default=[])

    g = p.add_argument_group('Inventory')
    g.add_argument('-i', '--inventory')
    g.add_argument('--hosts', '-H',
                   default='all')

    g = p.add_argument_group('Identity')
    g.add_argument('--sudo', '-s',
                   action='store_true',
                   dest='become')
    g.add_argument('--become', '-b',
                   action='store_true')
    g.add_argument('--user', '-u')

    p.add_argument('role')

    p.set_defaults(gather=True)
    return p.parse_args()


def main():
    args = parse_args()
    template = jinja2.Template(role_playbook)

    with tempfile.NamedTemporaryFile(dir='.') as fd:
        fd.write(template.render(
            role=args.role,
            hosts=args.hosts,
            gather=args.gather,
        ))

        fd.flush()

        ap_args = [('-e', x) for x in args.extra_vars]
        cmdvec = ['ansible-playbook', fd.name]
        if args.inventory:
            cmdvec.extend(('-i', args.inventory))

        if args.become:
            cmdvec.append('-b')

        if args.user:
            cmdvec.extend(('-u', args.user))

        for i in range(args.verbose):
            cmdvec.append('-v')

        for arg in ap_args:
            cmdvec.extend(arg)

        subprocess.check_call(cmdvec)


if __name__ == '__main__':
    main()
